version: '3.8'


services:
  # Service pour la base de données MySQL
  mysqldb:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    env_file: ./.env  # Chargement des variables d'environnement depuis un fichier .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql  # Persistance des données dans un volume Docker

  # Service pour l'application Kaddem
  app:
    depends_on:
      - mysqldb  # L'application dépend du service mysqldb
    image: zeinebmaatalli/kaddem  # Ton image Docker
    container_name: kaddem
    restart: on-failure
    env_file: ./.env  # Chargement des variables d'environnement
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT  # Port mappé depuis l'environnement
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2  # Cache Maven pour la construction de l'application
    stdin_open: true
    tty: true

# Définition du volume persistant pour la base de données
volumes:
  db:
  
