version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddem/db
    volumes:
      - db:/var/lib/mysql

  kaddem:
    image: zeinebmaatalli/kaddem  # Utilisation de l'image Docker que tu as créée
    container_name: kaddem
    ports:
      - "8082:8082"

volumes:
  db:
